### ISSUE TITLE
It would be nice if this depended on the newer gflags library

### ISSUE THREAD

**Issue by jcftang-r7** [benley/python-glog#3]
See https://github.com/google/python-gflags, it would be nice if it depended on the newer version of gflags

**Comment by benley** [comment]
It looks like python-gflags 3.0 included a whole bunch of backwards-incompatible changes.  Since this library doesn't specifically need any of the newer functionality, I think I would prefer to leave the version requirement loose here and allow downstream code to specify the newer gflags version if desired.

I will make sure that python-glog is compatible with the newest version of python-gflags, at least!
